#ifndef LIGHTSIDE_SHADER_FEATURES_INCLUDED
#define LIGHTSIDE_SHADER_FEATURES_INCLUDED

#ifndef LIGHTSIDE_SHADER_VARIANTS
#define LIGHTSIDE_GLYPHS
#define LIGHTSIDE_SHAPES
#define LIGHTSIDE_ATLAS_QUADS
#endif

#if defined(LIGHTSIDE_SHAPES) || defined(LIGHTSIDE_ROUNDED_RECTANGLES)
#define LIGHTSIDE_SHAPE_SURFACE
#endif

#endif
